import type { Metadata } from 'next'
import { Sen } from 'next/font/google'
import './globals.css'
import Session from '@src/components/Session'

const inter = Sen({
  weight: '400',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Auth',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gradient-to-tr from-emerald-400 to-cyan-400 overflow-x-hidden`}>
        <Session>
          {children}
        </Session>
      </body>
    </html>
  )
}
